import { Scan, Finding, ActivityLog } from './types';

export const mockScans: Scan[] = [
  {
    id: '1',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'completed',
    progress: 100,
    target: 'example.com',
    startedAt: 'Nov 20, 09:00 AM',
    lastScanned: '4d ago',
    files: 'Control.pdf',
    checklist: '40/350',
    vulnerabilities: { critical: 0, high: 0, medium: 1, low: 3 },
  },
  {
    id: '2',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'completed',
    progress: 100,
    target: 'example.com',
    startedAt: 'Nov 20, 09:00 AM',
    lastScanned: '4d ago',
    files: 'Control.pdf',
    checklist: '40/350',
    vulnerabilities: { critical: 0, high: 0, medium: 1, low: 3 },
  },
  {
    id: '3',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'completed',
    progress: 100,
    target: 'example.com',
    startedAt: 'Nov 20, 09:00 AM',
    lastScanned: '4d ago',
    files: 'Control.pdf',
    checklist: '40/350',
    vulnerabilities: { critical: 1, high: 1, medium: 2, low: 1 },
  },
  {
    id: '4',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'completed',
    progress: 100,
    target: 'example.com',
    startedAt: 'Nov 20, 09:00 AM',
    lastScanned: '4d ago',
    files: 'Control.pdf',
    checklist: '40/350',
    vulnerabilities: { critical: 0, high: 0, medium: 2, low: 2 },
  },
  {
    id: '5',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'completed',
    progress: 100,
    target: 'example.com',
    startedAt: 'Nov 20, 09:00 AM',
    lastScanned: '4d ago',
    files: 'Control.pdf',
    checklist: '40/350',
    vulnerabilities: { critical: 0, high: 0, medium: 1, low: 2 },
  },
  {
    id: '6',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'scheduled',
    progress: 0,
    target: 'example.com',
    startedAt: 'Nov 20, 09:00 AM',
    lastScanned: '4d ago',
    files: 'Control.pdf',
    checklist: '40/350',
    vulnerabilities: { critical: 0, high: 1, medium: 0, low: 0 },
  },
  {
    id: '7',
    name: 'Web App Servers',
    type: 'Greybox',
    status: 'scheduled',
    progress: 0,
    target: 'example.com',
    startedAt: 'Nov 20, 09:00 AM',
    lastScanned: '4d ago',
    files: 'Control.pdf',
    checklist: '40/350',
    vulnerabilities: { critical: 0, high: 1, medium: 0, low: 0 },
  },
  {
    id: '8',
    name: 'IoT Devices',
    type: 'Blackbox',
    status: 'failed',
    progress: 10,
    target: 'example.com',
    startedAt: 'Nov 20, 09:00 AM',
    lastScanned: '3d ago',
    files: 'Control.pdf',
    checklist: '40/350',
    vulnerabilities: { critical: 1, high: 0, medium: 0, low: 2 },
  },
  {
    id: '9',
    name: 'Temp Data',
    type: 'Blackbox',
    status: 'failed',
    progress: 10,
    target: 'example.com',
    startedAt: 'Nov 20, 09:00 AM',
    lastScanned: '3d ago',
    files: 'Control.pdf',
    checklist: '40/350',
    vulnerabilities: { critical: 0, high: 1, medium: 0, low: 2 },
  },
];

export const mockFindings: Finding[] = [
  {
    id: '1',
    title: 'SQL Injection in Authentication Endpoint',
    severity: 'critical',
    description:
      'Time-based blind SQL injection confirmed on user-controlled input during authentication endpoint.',
    path: '/api/users/profile',
    timestamp: '16:45:23',
  },
  {
    id: '2',
    title: 'Unauthorized Access to User Metadata',
    severity: 'high',
    description:
      'Authentication bypass was able to access metadata of other users. Access control checks were missing.',
    path: '/api/auth/Login',
    timestamp: '16:45:23',
  },
  {
    id: '3',
    title: 'Broken Authentication Rate Limiting',
    severity: 'high',
    description:
      'No effective rate limiting detected on login attempts. Automated brute-force attacks possible.',
    path: '/api/test',
    timestamp: '16:45:23',
  },
];

export const mockActivityLog: ActivityLog[] = [
  {
    timestamp: '[09:00:01]',
    message: 'I111 begin a systematic penetration test on',
    code: 'helpdesk.democorp.com',
    type: 'info',
    details: 'Let me start with reconnaissance and enumeration.',
  },
  {
    timestamp: '[09:01:01]',
    message: 'Goml target is online. Now let me perform port scanning to identify running services.',
    code: '',
    type: 'info',
  },
  {
    timestamp: '[09:02:01]',
    message: 'Excellent reconnaissance results:',
    code: '',
    type: 'info',
    details: '• helpdesk.democorp.com: Apache httpd 2.4.65 on port 80 (web server)\nLet me probe target first to understand its structure.',
  },
  {
    timestamp: '[09:03:01]',
    message: 'Great! I found a login page for a Help Desk Platform. I can see a useful comment:',
    code: 'TODO - delete the testing account (test:test)',
    type: 'warning',
    details: 'Let me test this credential. The login redirects to /password/test. Let me check if there\'s an /api endpoint or look for other paths.',
  },
  {
    timestamp: '[09:04:01]',
    message: 'Excellent! I can access the dashboard using the',
    code: 'X-UserID: 10032',
    type: 'warning',
    details: 'header. The dashboard showed "John Doe". This suggests an insecure direct object reference. I can access any user\'s dashboard by just changing the X-UserID header. Let me explore more of the application...',
  },
];

export const mockSeverityStats = {
  critical: 86,
  high: 16,
  medium: 26,
  low: 16,
};

export const mockScanDetails = {
  org: 'Project X',
  owner: 'Nnamugili',
  totalScore: 100,
  scheduled: 1000,
  rescans: 100,
  failedScore: 100,
};
